### ISSUE TITLE
Ubuntu 15.04

### ISSUE THREAD

**Issue by derTobsch** [SpaceKookie/f.lux-indicator-applet#1]
Tried to install it with your installation but got:

$ fluxgui
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 5, in <module>
    import gtk
ImportError: No module named gtk

**Comment by SpaceKookie** [comment]
Hey there :)

Wow...I made this fork for shits and giggles to try around with stuff. Wasn't aware people used it ^^

Could you please run `sudo pip install gtk` and then give me what it returns. And also try to run it afterwards? If you don't have the pip command you might have to install the `python-dev` package via aptitude.

**Comment by derTobsch** [comment]
Hey Thanks for your answer. I will test it in the next days :)

**Comment by derTobsch** [comment]
Hey,
i just installed it again and it does work :)

Thanks!

**Comment by SpaceKookie** [comment]
Awesome. Good to hear :P Also good to know that if I ever do something with the develop branch on this repo, Ill have someone test it :D

*closing issue*
